name: Main workflow

on: 
  push:
  # workflow_run:
  #   workflows: ["Second Workflow", "third Workflow"]
  #   types:
  #     - completed

concurrency:
  group: main-workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test code base
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Check Workflow Status
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "failure" ]; then
            # Cancel other workflows
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/cancel
          fi
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore NPM cache
        uses: ./.github/actions/cache-npm
        with:
          restore-only: true

      - name: Run test
        run: npm run test

      - name: Create fail-fast indicator
        if: failure()
        run: echo "fail" > fail-fast.txt

      - name: Upload fail-fast indicator
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: fail-fast
          path: fail-fast.txt