name: Main workflow

on: 
  push:
  # workflow_run:
  #   workflows: ["Second Workflow", "third Workflow"]
  #   types:
  #     - completed

concurrency:
  group: main-workflow-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  test:
    name: Test code base
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore NPM cache
        uses: ./.github/actions/cache-npm
        with:
          restore-only: true

      - name: Run test
        run: npm run test

      - name: Create fail-fast indicator
        if: failure()
        run: echo "fail" > fail-fast.txt

      - name: Upload fail-fast indicator
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: fail-fast
          path: fail-fast.txt