name: Monitor Workflows

on:
  workflow_run:
    workflows:
      - '*'  # Monitor all workflows
    types:
      - completed

jobs:
  cancel_on_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Cancel Workflows
        uses: stefanzweifel/git-auto-cancel-action@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
