name: Monitor Workflows

on:
  workflow_run:
    workflows:
      - '*'  # Monitor all workflows
    types:
      - completed

jobs:
  cancel_on_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Get Workflow Runs
          id: get_workflow_runs
          run: |
            echo "::set-output name=runs::$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -X GET https://api.github.com/repos/${{ github.repository }}/actions/runs)"

      - name: Cancel Workflows
          run: |
            runs="${{ steps.get_workflow_runs.outputs.runs }}"
            for id in $(echo "${runs}" | jq -r '.workflow_runs[] | select(.id != ${{ github.event.workflow_run.id }}) | .id'); do
              curl -X POST \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/actions/runs/${id}/cancel
            done
