name: Monitor Workflows

on:
  workflow_run:
    workflows:
      - '*'  # Monitor all workflows
    types:
      - completed

jobs:
  cancel_on_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Get Workflow Runs
        id: get_workflow_runs
        run: |
          runs=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -X GET https://api.github.com/repos/${{ github.repository }}/actions/runs | jq -c '.workflow_runs[] | {id: .id}')

          echo "${runs}" > runs.json

          echo "RUNS_JSON=$(cat runs.json)" >> $GITHUB_ENV

      - name: Cancel Workflows
        run: |
          for id in $(jq -r '.[].id' <<< "${RUNS_JSON}"); do
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs/${id}/cancel
          done
