name: Second Workflow

on:
  push:

concurrency:
  group: second-workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conditional-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delay for 40 seconds
        run: sleep 40s

      - name: Delay for 10 seconds
        run: sleep 50s


