name: Second Workflow

on:
  push:
  repository_dispatch:
    types: [fail-fast]

jobs:
  conditional-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delay for 50 seconds
        run: sleep 50s


