name: third Workflow

on:
  push:
    paths: ["*","changes-folder/**", ".github/**"]
  # workflow_run:
  #   workflows: ["Second Workflow", "third Workflow"]
  #   types:
  #     - completed

concurrency:
  group: third-workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conditional-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run this is there's change in change folder
        if: ${{ contains(github.event.head_commit.message, 'changes-folder') }}
        run: sleep 50s