name: third Workflow

on:
  push:
    paths: ["*","changes-folder/**", ".github/**"]
  # workflow_run:
  #   workflows: ["Second Workflow", "third Workflow"]
  #   types:
  #     - completed

concurrency:
  group: third-workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conditional-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Check Workflow Status
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "failure" ]; then
            # Cancel other workflows
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/cancel
          fi
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run this is there's change in change folder
        if: ${{ contains(github.event.head_commit.message, 'changes-folder') }}
        run: sleep 50s